"""
src/preprocessing.py
Sklearn-compatible preprocessing pipeline for the Kickstarter ML project.
Builds a ColumnTransformer that handles numeric scaling and encodes categoricals.
"""
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


# These are the engineered numeric features used in the model
NUMERIC_FEATURES = [
    "log_goal",
    "duration_days",
    "prep_days",
    "has_video",
    "blurb_length",
    "name_length",
    "blurb_word_count",
    "name_has_number",
    "goal_is_round",
    "is_usd",
    "launched_month",
    "launched_dayofweek",
    "launched_year",
    "staff_pick",
    "goal_per_day",
    "is_california",
    "cat_name_encoded",
]

# OHE columns added dynamically (country_*, parent_*)
OHE_PREFIX_PATTERNS = ["country_", "parent_"]


def get_feature_columns(df: pd.DataFrame) -> list:
    """
    Dynamically get all feature columns present in df.
    Includes numeric features and any OHE columns generated by build_features.
    """
    base = [c for c in NUMERIC_FEATURES if c in df.columns]
    ohe = [c for c in df.columns
           if any(c.startswith(p) for p in OHE_PREFIX_PATTERNS)]
    return base + ohe


def build_numeric_pipeline() -> Pipeline:
    """
    Pipeline for numeric features:
      1. SimpleImputer (median) — fills any remaining NaN
      2. StandardScaler — zero mean, unit variance
    """
    return Pipeline([
        ("impute", SimpleImputer(strategy="median")),
        ("scale", StandardScaler()),
    ])


def build_preprocessor(feature_cols: list) -> ColumnTransformer:
    """
    Build a ColumnTransformer that scales all numeric features.
    OHE binary columns (0/1) are passed through without scaling when used
    with tree-based models; for SVM/LR they need scaling.
    """
    return ColumnTransformer(
        transformers=[
            ("num", build_numeric_pipeline(), feature_cols),
        ],
        remainder="drop",
    )


def prepare_Xy(df: pd.DataFrame, feature_cols: list = None):
    """
    Extract feature matrix X and target vector y from a dataframe.

    Parameters
    ----------
    df : pd.DataFrame
        Engineered dataframe with 'success' column.
    feature_cols : list, optional
        If None, auto-detected via get_feature_columns(df).

    Returns
    -------
    X : pd.DataFrame, y : pd.Series
    """
    if feature_cols is None:
        feature_cols = get_feature_columns(df)
    missing = [c for c in feature_cols if c not in df.columns]
    if missing:
        print(f"[WARN] Missing feature columns (will be zeros): {missing}")
        for m in missing:
            df[m] = 0
    X = df[feature_cols].copy()
    y = df["success"].copy() if "success" in df.columns else None
    return X, y
